FROM arm64v8/fedora:41

LABEL MAINTAINER Yonier Gomez yonieer13@gmail.com, version: 4.8.6.0

RUN dnf -y update && dnf -y install \
https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.6.0/emby-server-rpm_4.8.6.0_aarch64.rpm \
    && dnf clean all

RUN mkdir -p multimedia/{videos,musica,peliculas}

WORKDIR /multimedia

EXPOSE 8096 8920 7359/udp 1900/udp

CMD /opt/emby-server/bin/emby-server