name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_push_image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - actuated-aarch64

    steps:
    - uses: actions/checkout@v3
      name: Download code from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}

    - name: Set up QEMU
      if: matrix.os == 'actuated-aarch64'
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use
      shell: bash

    - name: Run Docker Build and Push
      run: |
        DOCKER_TAG=""
        if [ "${{ matrix.os }}" == "actuated-aarch64" ]; then
          DOCKER_TAG="4.7.14.0-arm"
        else
          DOCKER_TAG="4.7.14.0"
        fi
        echo "Using Docker Tag: $DOCKER_TAG"
        
        docker buildx build \
          --file Dockerfile \
          --tag "neytor/emby-neytor:$DOCKER_TAG" \
          --push .
        docker image ls
      shell: bash
