name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_push_image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - actuated-aarch64

    steps:
    - uses: actions/checkout@v3
      name: Download code from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}

    - name: Set Tag
      run: |
        if [ ${{ matrix.os }} == 'actuated-aarch64' ]; then
          export DOCKER_TAG="4.7.14.0-arm"
        else
          export DOCKER_TAG="4.7.14.0"
        fi
        
        echo "Using Docker Tag: $DOCKER_TAG"
      
    - name: Build and push the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag neytor/emby-neytor:$DOCKER_TAG
        docker image ls
        docker push neytor/emby-neytor:$DOCKER_TAG
