name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag emby-neytor:4.7.14.0 && docker push emby-neytor:4.7.14.0

      
    

