name: Docker Image CI ARM - Emby Server

on:
  workflow_dispatch: # Agrega esta entrada para habilitar la ejecución manual
    branches: [ "master", "main" ] # Opcional: restringe las ramas donde se puede ejecutar

jobs:

  build_push_image:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/emby-neytor:arm && 
        docker image ls && docker push neytor/emby-neytor:arm

    - name: Build and push the Docker image with tag
      run: |
        docker build . --file Dockerfile --tag neytor/emby-neytor:arm.v4.7.14.0 && \
        docker image ls && docker push neytor/emby-neytor:arm.v4.7.14.0
      
    

