name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/emby-neytor && 
        docker image ls && docker push neytor/emby-neytor

    - name: Build and push the Docker image with tag
      run: |
        docker build . --file Dockerfile --tag neytor/emby-neytor:4.7.14.0 && \
        docker image ls && docker push neytor/emby-neytor:4.7.14.0
      
    

